export const SAVE_CUSTOMER_INFORMATION = 'SAVE_CUSTOMER_INFORMATION';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
export const SAVE_USER = 'SAVE_USER'